language: python
python:
    - "2.7"
    - "pypy"
    - "pypy3"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
install:
    - pip install -r requirements-dev.txt
script:
    - "nosetests tests"
jobs:
    allow_failures:
        - python: "2.7"
        - python: "pypy"